CREATE TABLE IF NOT EXISTS tbl_employee_personal_detail (
    id UUID PRIMARY KEY,
    marital_status VARCHAR(10),
    marriage_date DATE,
    blood_group VARCHAR(5),
    nationality VARCHAR(50),
    physically_challenged BOOLEAN,
    disability_details BOOLEAN,
    father_name VARCHAR(100),
    mother_name VARCHAR(100),
    spouse_name VARCHAR(100),
    spouse_gender VARCHAR(10),
    residence_number INT,
    social_media_handles TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tbl_organisation_detail (
    id UUID PRIMARY KEY,
    legal_entity_name VARCHAR(255),
    auth_signatory_name VARCHAR(255),
    auth_signatory_designation VARCHAR(255),
    auth_signatory_email VARCHAR(255) ,
    auth_signatory_father_name VARCHAR(255),
    corporation_date DATE,
    cin VARCHAR(50) ,
    bank_type VARCHAR(50),
    bank_name VARCHAR(255),
    bank_code BIGINT,
    swift_code VARCHAR(50),
    account_number VARCHAR(50),
    ifsc_code VARCHAR(50),
    branch_name VARCHAR(255),
    name_on_account VARCHAR(255),
    pan VARCHAR(20),
    tan VARCHAR(20),
    tan_circle_number VARCHAR(50),
    corporate_income_tax_locations TEXT,
    compliance_code VARCHAR(100),
    pf_establishment_id VARCHAR(50),
    pf_number VARCHAR(50),
    pf_registration_date DATE,
    esi_number VARCHAR(50),
    esi_registration_date DATE,
    pt_establishment_id VARCHAR(50),
    pt_number VARCHAR(50),
    pt_registration_date DATE,
    lwf_establishment_id VARCHAR(50),
    lwf_registration_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tbl_organisation_locations (
    id UUID PRIMARY KEY,
    country_code VARCHAR(10),
    country_name VARCHAR(100),
    dial_code VARCHAR(10),
    currency_code VARCHAR(20),
    auth_signatory_designation VARCHAR(255),
    cin VARCHAR(50) ,
    state_code VARCHAR(10),
    state_name VARCHAR(100),
    location_name VARCHAR(255),
    location_code VARCHAR(50) ,
    is_head_office BOOLEAN DEFAULT FALSE,
    is_registered_office BOOLEAN DEFAULT FALSE,
    is_branch BOOLEAN DEFAULT FALSE,
    address_line_1 VARCHAR(255),
    address_line_2 VARCHAR(255),
    locality VARCHAR(100),
    city VARCHAR(100),
    pincode BIGINT,
    email VARCHAR(255),
    phone BIGINT,
    gstin VARCHAR(50),
    timezone VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tbl_organisation_departments (
    id UUID PRIMARY KEY,
    type_name VARCHAR(255),
    type_code VARCHAR(50),
    description TEXT,
    auth_signatory_designation VARCHAR(255),
    cin VARCHAR(50),
    dept_code VARCHAR(50) UNIQUE,
    dept_name VARCHAR(255),
    parent_dept_type_code VARCHAR(50),
    parent_dept_code VARCHAR(50),
    cost_center_code VARCHAR(50),
    dept_description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tbl_employee_data (
    id UUID PRIMARY KEY,
    type_name VARCHAR(255),
    type_code VARCHAR(50),
    description TEXT,
    auth_signatory_designation VARCHAR(255),
    cin VARCHAR(50) ,
    title_name VARCHAR(100),
    title_code VARCHAR(50),
    title_description TEXT,
    grade_level INT,
    employee_id UUID,
    dept_type_code VARCHAR(50) ,
    dept_code VARCHAR(50) ,
    work_location_code VARCHAR(50),
    work_location_city VARCHAR(255),
    title VARCHAR(10),
    first_name VARCHAR(100),
    middle_name VARCHAR(100),
    last_name VARCHAR(100),
    display_name VARCHAR(255),
    date_of_birth DATE,
    gender VARCHAR(40),
    official_email VARCHAR(255),
    personal_email VARCHAR(255),
    mobile_number BIGINT,
    emergency_contact_name VARCHAR(255),
    emergency_contact_relationship VARCHAR(100),
    emergency_contact_number BIGINT,
    date_joined DATE,
    probation_end_date DATE,
    confirmation_date DATE,
    contract_end_date DATE,
    reporting_manager_employee_number UUID,
    reporting_manager_first_name VARCHAR(100),
    notice_period_days BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tbl_employee_financial_detail (
    id UUID PRIMARY KEY,
    employee_number UUID PRIMARY KEY,
    employee_first_name VARCHAR(255),
    compliance_code VARCHAR(100),
    org_pf_number VARCHAR(50),
    bank_type VARCHAR(100),
    bank_code VARCHAR(50),
    swift_code VARCHAR(50),
    account_number BIGINT NOT NULL UNIQUE,
    account_type VARCHAR(50),
    ifsc_code VARCHAR(50),
    branch_name VARCHAR(255),
    name_on_account VARCHAR(255),
    salary_payment_mode VARCHAR(50),
    pf_detail_available BOOLEAN DEFAULT FALSE,
    pf_number VARCHAR(50),
    pf_joining_date DATE,
    employee_contribution_to_pf VARCHAR(50),
    esi_detail_available BOOLEAN DEFAULT FALSE,
    esi_eligible BOOLEAN DEFAULT FALSE,
    employee_esi_number BIGINT UNIQUE,
    lwf_eligible BOOLEAN DEFAULT FALSE,
    aadhar_number BIGINT UNIQUE,
    dob_in_aadhar DATE,
    full_name_in_aadhar VARCHAR(255),
    gender_in_aadhar VARCHAR(50),
    pan_available BOOLEAN DEFAULT FALSE,
    pan_number VARCHAR(20) UNIQUE,
    full_name_in_pan VARCHAR(255),
    dob_in_pan DATE,
    parent_name_in_pan VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tbl_salary_component_master (
    id UUID PRIMARY KEY ,
    component_name VARCHAR(255) NOT NULL,
    auth_signatory_designation VARCHAR(255),
    cin VARCHAR(50) NOT NULL,
    component_code VARCHAR(100) UNIQUE NOT NULL,
    component_category VARCHAR(100),
    component_type VARCHAR(100),
    calculation_type VARCHAR(100),
    calculation_basis VARCHAR(255),
    calculation_formula TEXT,
    calculation_frequency VARCHAR(100),
    is_taxable BOOLEAN DEFAULT FALSE,
    consider_for_ctc BOOLEAN DEFAULT FALSE,
    consider_for_esi BOOLEAN DEFAULT FALSE,
    consider_for_pf BOOLEAN DEFAULT FALSE,
    consider_for_bonus BOOLEAN DEFAULT FALSE,
    min_value VARCHAR(50),
    max_value VARCHAR(50),
    rounding_factor INT DEFAULT 0,
    print_name VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS tbl_salary_structure (
    id UUID PRIMARY KEY,
    structure_name VARCHAR(255) NOT NULL,
    auth_signatory_designation VARCHAR(255),
    cin VARCHAR(50) NOT NULL,
    structure_code VARCHAR(100) UNIQUE NOT NULL,
    description TEXT,
    min_ctc BIGINT NOT NULL,
    max_ctc BIGINT NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    is_default BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tbl_salary_structure_component (
    id UUID PRIMARY KEY,
    structure_name VARCHAR(255) NOT NULL,
    structure_code VARCHAR(100) NOT NULL,
    component_code VARCHAR(100) NOT NULL,
    component_category VARCHAR(100),
    calculation_priority INT NOT NULL,
    percentage_of_basic DECIMAL(10,2),
    percentage_of_ctc DECIMAL(10,2),
    min_value BIGINT,
    max_value BIGINT,
    default_value BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS tbl_employee_salary (
    id UUID PRIMARY KEY,
    employee_number UUID NOT NULL,
    employee_first_name VARCHAR(255) NOT NULL,
    structure_name VARCHAR(255) NOT NULL,
    structure_code VARCHAR(100) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE NOT NULL,
    annual_ctc BIGINT NOT NULL,
    monthly_ctc BIGINT NOT NULL,
    basic_percentage DECIMAL(5,2),
    hra_percentage DECIMAL(5,2),
    revision_type VARCHAR(50),
    revision_reason TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS tbl_payroll_cycles (
    id UUID PRIMARY KEY,
    cycle_name VARCHAR(255) NOT NULL,
    auth_signatory_designation VARCHAR(255),
    cin VARCHAR(50) NOT NULL,
    start_day INT CHECK (start_day BETWEEN 1 AND 31),
    end_day INT CHECK (end_day BETWEEN 1 AND 31),
    processing_day INT CHECK (processing_day BETWEEN 1 AND 31),
    payment_day INT CHECK (payment_day BETWEEN 1 AND 31),
    consider_previous_month BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS tbl_payroll_run (
    id UUID PRIMARY KEY,
    cycle_name VARCHAR(255) NOT NULL,
    auth_signatory_designation VARCHAR(255),
    cin VARCHAR(50) NOT NULL,
    cycle_start_day INT CHECK (cycle_start_day BETWEEN 1 AND 31),
    run_day INT CHECK (run_day BETWEEN 1 AND 31),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_employees BIGINT NOT NULL,
    total_gross BIGINT NOT NULL,
    total_deduction BIGINT NOT NULL,
    total_net_pay BIGINT NOT NULL,
    status VARCHAR(50) CHECK (status IN ('Pending', 'Processing', 'Completed', 'Failed')),
    locked BOOLEAN DEFAULT FALSE,
    processed_by_emp_number UUID,
    processed_by_emp_first_name VARCHAR(255),
    approved_by_emp_number UUID,
    approved_by_emp_first_name VARCHAR(255),
    remarks TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



